// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlcgenerate

import (
	"time"
)

// イベント: Firebaseトークンの確認
type FirebaseTokenVerify struct {
	// Firebaseユーザーの一意な識別子ULID
	FirebaseUserID string `json:"firebaseUserID"`
	// FirebaseのユーザーID
	Uid string `json:"uid"`
	// Firebaseユーザーのメールアドレス
	Email string `json:"email"`
	// Firebaseトークンの確認日時
	VerifiedTime time.Time `json:"verifiedTime"`
}

// リソース: サービスに接続しているFirebaseユーザー
type FirebaseUser struct {
	// Firebaseユーザーの一意な識別子ULID
	ID string `json:"id"`
	// FirebaseのユーザーID
	Uid string `json:"uid"`
	// Firebaseユーザーのメールアドレス
	Email string `json:"email"`
}
