// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: shiori_index.sql

package sqlcgenerate

import (
	"context"
)

const listPost = `-- name: ListPost :many
SELECT id FROM post
`

func (q *Queries) ListPost(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
