# Generated by Django 2.2.9 on 2020-01-31 16:39

import apiv1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=150, null=True, verbose_name='自己紹介')),
                ('homeimage', models.ImageField(blank=True, null=True, upload_to=apiv1.models.get_homeimage_path, verbose_name='ホーム画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypage_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'db_table': 'mypage',
            },
        ),
    ]
