# Generated by Django 2.2.9 on 2020-02-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypage',
            old_name='intro',
            new_name='introduction',
        ),
    ]
