# Generated by Django 2.2.10 on 2020-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='share_id',
            field=models.CharField(editable=False, max_length=32, verbose_name='選択肢共通ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_id',
            field=models.CharField(editable=False, max_length=32, verbose_name='選択肢共通ID'),
        ),
    ]
