# Generated by Django 2.2.10 on 2020-02-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
    ]
