# Generated by Django 2.2.10 on 2020-02-19 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_remove_poll_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='answer',
            field=models.CharField(editable=False, max_length=16, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='選択肢'),
        ),
    ]
