# Generated by Django 2.2.10 on 2020-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20200219_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='share_id',
            field=models.UUIDField(editable=False, verbose_name='選択肢共通ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_id',
            field=models.UUIDField(editable=False, verbose_name='選択肢共通ID'),
        ),
    ]
