# Generated by Django 2.2.10 on 2020-02-15 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20200216_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='num_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小計1'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='num_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小計2'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='num_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小計3'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='num_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小計4'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='select',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='投票先'),
        ),
    ]
