# Generated by Django 2.2.9 on 2020-02-11 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20200201_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mypage_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
