# Generated by Django 2.2.10 on 2020-02-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20200216_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_post', to='apiv1.Post', verbose_name='投稿'),
        ),
    ]
