version: "3"
services: 
    back:
        build: .
        ports: 
            - "8000:8000"
        command: gunicorn config.wsgi -b 0.0.0.0:8000
        depends_on: 
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata: