version: "3"
services: 
    back:
        build: "./"
        ports: 
            - "8000:8000"
        volumes:
            - "staticdata:/code/static/"
            - "./:/code/"
        # command: "gunicorn config.wsgi -b 0.0.0.0:8000"           # 本番環境
        command: "python3 manage.py runserver 0.0.0.0:8000"         # テスト環境
        depends_on: 
            - db
    db:
        image: postgres:12.1
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "5432:5432"
        volumes:
            - "dbdata:/var/lib/postgresql/data"
    nginx:
        build: "./nginx/"
        ports:
            - "80:80"
        volumes:
            - "staticdata:/opt/apps/static/"
        depends_on: 
            - back

volumes:
    dbdata:
    staticdata: