// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Hirochon/Shappar/go-server/internal/infrastructure/firebaseuserinfrastructure (interfaces: FirebaseUserStoreTxBeginner,FirebaseUserStoreTx,FirebaseUserStoreQueries)
//
// Generated by this command:
//
//	mockgen -destination=mock_firebase_user_store_test.go -package=firebaseuserinfrastructure . FirebaseUserStoreTxBeginner,FirebaseUserStoreTx,FirebaseUserStoreQueries
//

// Package firebaseuserinfrastructure is a generated GoMock package.
package firebaseuserinfrastructure

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlcgenerate "github.com/Hirochon/Shappar/go-server/internal/infrastructure/sqlc/sqlcgenerate"
	gomock "go.uber.org/mock/gomock"
)

// MockFirebaseUserStoreTxBeginner is a mock of FirebaseUserStoreTxBeginner interface.
type MockFirebaseUserStoreTxBeginner struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseUserStoreTxBeginnerMockRecorder
	isgomock struct{}
}

// MockFirebaseUserStoreTxBeginnerMockRecorder is the mock recorder for MockFirebaseUserStoreTxBeginner.
type MockFirebaseUserStoreTxBeginnerMockRecorder struct {
	mock *MockFirebaseUserStoreTxBeginner
}

// NewMockFirebaseUserStoreTxBeginner creates a new mock instance.
func NewMockFirebaseUserStoreTxBeginner(ctrl *gomock.Controller) *MockFirebaseUserStoreTxBeginner {
	mock := &MockFirebaseUserStoreTxBeginner{ctrl: ctrl}
	mock.recorder = &MockFirebaseUserStoreTxBeginnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseUserStoreTxBeginner) EXPECT() *MockFirebaseUserStoreTxBeginnerMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockFirebaseUserStoreTxBeginner) Begin() (FirebaseUserStoreTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(FirebaseUserStoreTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockFirebaseUserStoreTxBeginnerMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockFirebaseUserStoreTxBeginner)(nil).Begin))
}

// MockFirebaseUserStoreTx is a mock of FirebaseUserStoreTx interface.
type MockFirebaseUserStoreTx struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseUserStoreTxMockRecorder
	isgomock struct{}
}

// MockFirebaseUserStoreTxMockRecorder is the mock recorder for MockFirebaseUserStoreTx.
type MockFirebaseUserStoreTxMockRecorder struct {
	mock *MockFirebaseUserStoreTx
}

// NewMockFirebaseUserStoreTx creates a new mock instance.
func NewMockFirebaseUserStoreTx(ctrl *gomock.Controller) *MockFirebaseUserStoreTx {
	mock := &MockFirebaseUserStoreTx{ctrl: ctrl}
	mock.recorder = &MockFirebaseUserStoreTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseUserStoreTx) EXPECT() *MockFirebaseUserStoreTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockFirebaseUserStoreTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockFirebaseUserStoreTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).Commit))
}

// ExecContext mocks base method.
func (m *MockFirebaseUserStoreTx) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockFirebaseUserStoreTxMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).ExecContext), varargs...)
}

// PrepareContext mocks base method.
func (m *MockFirebaseUserStoreTx) PrepareContext(arg0 context.Context, arg1 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", arg0, arg1)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockFirebaseUserStoreTxMockRecorder) PrepareContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).PrepareContext), arg0, arg1)
}

// QueryContext mocks base method.
func (m *MockFirebaseUserStoreTx) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockFirebaseUserStoreTxMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockFirebaseUserStoreTx) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockFirebaseUserStoreTxMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).QueryRowContext), varargs...)
}

// Rollback mocks base method.
func (m *MockFirebaseUserStoreTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockFirebaseUserStoreTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockFirebaseUserStoreTx)(nil).Rollback))
}

// MockFirebaseUserStoreQueries is a mock of FirebaseUserStoreQueries interface.
type MockFirebaseUserStoreQueries struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseUserStoreQueriesMockRecorder
	isgomock struct{}
}

// MockFirebaseUserStoreQueriesMockRecorder is the mock recorder for MockFirebaseUserStoreQueries.
type MockFirebaseUserStoreQueriesMockRecorder struct {
	mock *MockFirebaseUserStoreQueries
}

// NewMockFirebaseUserStoreQueries creates a new mock instance.
func NewMockFirebaseUserStoreQueries(ctrl *gomock.Controller) *MockFirebaseUserStoreQueries {
	mock := &MockFirebaseUserStoreQueries{ctrl: ctrl}
	mock.recorder = &MockFirebaseUserStoreQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseUserStoreQueries) EXPECT() *MockFirebaseUserStoreQueriesMockRecorder {
	return m.recorder
}

// CreateFirebaseTokenVerify mocks base method.
func (m *MockFirebaseUserStoreQueries) CreateFirebaseTokenVerify(arg0 context.Context, arg1 sqlcgenerate.CreateFirebaseTokenVerifyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFirebaseTokenVerify", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFirebaseTokenVerify indicates an expected call of CreateFirebaseTokenVerify.
func (mr *MockFirebaseUserStoreQueriesMockRecorder) CreateFirebaseTokenVerify(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFirebaseTokenVerify", reflect.TypeOf((*MockFirebaseUserStoreQueries)(nil).CreateFirebaseTokenVerify), arg0, arg1)
}

// CreateFirebaseUser mocks base method.
func (m *MockFirebaseUserStoreQueries) CreateFirebaseUser(arg0 context.Context, arg1 sqlcgenerate.CreateFirebaseUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFirebaseUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFirebaseUser indicates an expected call of CreateFirebaseUser.
func (mr *MockFirebaseUserStoreQueriesMockRecorder) CreateFirebaseUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFirebaseUser", reflect.TypeOf((*MockFirebaseUserStoreQueries)(nil).CreateFirebaseUser), arg0, arg1)
}
