# Generated by Django 2.2.9 on 2020-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='born_at',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
