// Package oas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oas

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status *string `json:"status,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Iconimage *string `json:"iconimage,omitempty"`
	Options   *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
		Votes     *int    `json:"votes,omitempty"`
	} `json:"options,omitempty"`
	PostId      *string `json:"post_id,omitempty"`
	Question    *string `json:"question,omitempty"`
	SelectedNum *int    `json:"selected_num,omitempty"`
	Total       *int    `json:"total,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
	Voted       *bool   `json:"voted,omitempty"`
}

// Posts defines model for Posts.
type Posts struct {
	Posts *[]Post `json:"posts,omitempty"`
}

// User defines model for User.
type User struct {
	HomeImage    *string `json:"homeImage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// Users defines model for Users.
type Users struct {
	Users *[]User `json:"users,omitempty"`
}

// PostApiV1PostsJSONBody defines parameters for PostApiV1Posts.
type PostApiV1PostsJSONBody struct {
	Options *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
	} `json:"options,omitempty"`
	Question *string `json:"question,omitempty"`
}

// GetApiV1PostsPrivateParams defines parameters for GetApiV1PostsPrivate.
type GetApiV1PostsPrivateParams struct {
	// Q 検索キーワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetApiV1PostsPublicParams defines parameters for GetApiV1PostsPublic.
type GetApiV1PostsPublicParams struct {
	// Q 検索ワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Pid 追加読み込みの基準
	Pid *string `form:"pid,omitempty" json:"pid,omitempty"`
}

// PostApiV1PostsPostIdPollsJSONBody defines parameters for PostApiV1PostsPostIdPolls.
type PostApiV1PostsPostIdPollsJSONBody struct {
	Option *struct {
		SelectNum *int `json:"select_num,omitempty"`
	} `json:"option,omitempty"`
}

// PatchApiV1UsersUserIdJSONBody defines parameters for PatchApiV1UsersUserId.
type PatchApiV1UsersUserIdJSONBody struct {
	Homeimage    *string `json:"homeimage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// PostApiV1PostsJSONRequestBody defines body for PostApiV1Posts for application/json ContentType.
type PostApiV1PostsJSONRequestBody PostApiV1PostsJSONBody

// PostApiV1PostsPostIdPollsJSONRequestBody defines body for PostApiV1PostsPostIdPolls for application/json ContentType.
type PostApiV1PostsPostIdPollsJSONRequestBody PostApiV1PostsPostIdPollsJSONBody

// PatchApiV1UsersUserIdJSONRequestBody defines body for PatchApiV1UsersUserId for application/json ContentType.
type PatchApiV1UsersUserIdJSONRequestBody PatchApiV1UsersUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Your GET endpoint
	// (GET /api/v1/frendships/{userId}/followers)
	GetApiV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /api/v1/frendships/{userId}/following)
	GetApiV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string)

	// (DELETE /api/v1/friendships/{userId})
	DeleteApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (POST /api/v1/friendships/{userId})
	PostApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /api/v1/friendships/{userId})
	PutApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)
	// 疎通確認でHealthCheck
	// (GET /api/v1/health)
	GetApiV1Health(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/posts)
	PostApiV1Posts(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /api/v1/posts/private)
	GetApiV1PostsPrivate(w http.ResponseWriter, r *http.Request, params GetApiV1PostsPrivateParams)
	// Your GET endpoint
	// (GET /api/v1/posts/public)
	GetApiV1PostsPublic(w http.ResponseWriter, r *http.Request, params GetApiV1PostsPublicParams)
	// Your GET endpoint
	// (GET /api/v1/posts/public/rank)
	GetApiV1PostsPublicRank(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /api/v1/posts/public/{post_id})
	GetApiV1PostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (DELETE /api/v1/posts/{post_id})
	DeleteApiV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /api/v1/posts/{post_id})
	GetApiV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (POST /api/v1/posts/{post_id}/polls)
	PostApiV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /api/v1/users)
	GetApiV1Users(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/users)
	PostApiV1Users(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/users/{user_id})
	DeleteApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /api/v1/users/{user_id})
	GetApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PATCH /api/v1/users/{user_id})
	PatchApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /api/v1/users/{user_id}/posted)
	GetApiV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string)

	// (GET /api/v1/users/{user_id}/settings)
	GetApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /api/v1/users/{user_id}/settings)
	PutApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /api/v1/users/{user_id}/voted)
	GetApiV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Your GET endpoint
// (GET /api/v1/frendships/{userId}/followers)
func (_ Unimplemented) GetApiV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/frendships/{userId}/following)
func (_ Unimplemented) GetApiV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/friendships/{userId})
func (_ Unimplemented) DeleteApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/friendships/{userId})
func (_ Unimplemented) PostApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/v1/friendships/{userId})
func (_ Unimplemented) PutApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 疎通確認でHealthCheck
// (GET /api/v1/health)
func (_ Unimplemented) GetApiV1Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/posts)
func (_ Unimplemented) PostApiV1Posts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/posts/private)
func (_ Unimplemented) GetApiV1PostsPrivate(w http.ResponseWriter, r *http.Request, params GetApiV1PostsPrivateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/posts/public)
func (_ Unimplemented) GetApiV1PostsPublic(w http.ResponseWriter, r *http.Request, params GetApiV1PostsPublicParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/posts/public/rank)
func (_ Unimplemented) GetApiV1PostsPublicRank(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/posts/public/{post_id})
func (_ Unimplemented) GetApiV1PostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/posts/{post_id})
func (_ Unimplemented) DeleteApiV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/posts/{post_id})
func (_ Unimplemented) GetApiV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/posts/{post_id}/polls)
func (_ Unimplemented) PostApiV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/users)
func (_ Unimplemented) GetApiV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/users)
func (_ Unimplemented) PostApiV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/v1/users/{user_id})
func (_ Unimplemented) DeleteApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/users/{user_id})
func (_ Unimplemented) GetApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/v1/users/{user_id})
func (_ Unimplemented) PatchApiV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/users/{user_id}/posted)
func (_ Unimplemented) GetApiV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/users/{user_id}/settings)
func (_ Unimplemented) GetApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/v1/users/{user_id}/settings)
func (_ Unimplemented) PutApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /api/v1/users/{user_id}/voted)
func (_ Unimplemented) GetApiV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1FrendshipsUserIdFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1FrendshipsUserIdFollowers(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1FrendshipsUserIdFollowing operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1FrendshipsUserIdFollowing(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Health operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Health(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Posts operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Posts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Posts(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1PostsPrivate operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PostsPrivate(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1PostsPrivateParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1PostsPrivate(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1PostsPublic operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PostsPublic(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1PostsPublicParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "pid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pid", r.URL.Query(), &params.Pid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1PostsPublic(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1PostsPublicRank operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PostsPublicRank(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1PostsPublicRank(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1PostsPublicPostId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PostsPublicPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1PostsPublicPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1PostsPostId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1PostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1PostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1PostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1PostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1PostsPostIdPolls operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1PostsPostIdPolls(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Users operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Users(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Users(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Users operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Users(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Users(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UsersUserIdPosted operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UsersUserIdPosted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV1UsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV1UsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UsersUserIdVoted operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UsersUserIdVoted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/frendships/{userId}/followers", wrapper.GetApiV1FrendshipsUserIdFollowers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/frendships/{userId}/following", wrapper.GetApiV1FrendshipsUserIdFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/friendships/{userId}", wrapper.DeleteApiV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/friendships/{userId}", wrapper.PostApiV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/friendships/{userId}", wrapper.PutApiV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetApiV1Health)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/posts", wrapper.PostApiV1Posts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/posts/private", wrapper.GetApiV1PostsPrivate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/posts/public", wrapper.GetApiV1PostsPublic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/posts/public/rank", wrapper.GetApiV1PostsPublicRank)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/posts/public/{post_id}", wrapper.GetApiV1PostsPublicPostId)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/posts/{post_id}", wrapper.DeleteApiV1PostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/posts/{post_id}", wrapper.GetApiV1PostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/posts/{post_id}/polls", wrapper.PostApiV1PostsPostIdPolls)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users", wrapper.GetApiV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users", wrapper.PostApiV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/users/{user_id}", wrapper.DeleteApiV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{user_id}", wrapper.GetApiV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/users/{user_id}", wrapper.PatchApiV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{user_id}/posted", wrapper.GetApiV1UsersUserIdPosted)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{user_id}/settings", wrapper.GetApiV1UsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/users/{user_id}/settings", wrapper.PutApiV1UsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{user_id}/voted", wrapper.GetApiV1UsersUserIdVoted)
	})

	return r
}
