// Package oas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oas

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthSignResponse defines model for AuthSignResponse.
type AuthSignResponse struct {
	// Registered ユーザー作成済みかどうか
	Registered bool            `json:"registered"`
	User       *AuthSignedUser `json:"user,omitempty"`
}

// AuthSignedUser defines model for AuthSignedUser.
type AuthSignedUser struct {
	// Id ユーザーUUID
	Id openapi_types.UUID `json:"id"`

	// Name 表示名
	Name string `json:"name"`

	// ThumbnailUrl サムネイル画像URL
	ThumbnailUrl string `json:"thumbnail_url"`

	// UniqueId ユーザーが設定する任意ID
	UniqueId string `json:"unique_id"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status *string `json:"status,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Iconimage *string `json:"iconimage,omitempty"`
	Options   *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
		Votes     *int    `json:"votes,omitempty"`
	} `json:"options,omitempty"`
	PostId      *string `json:"post_id,omitempty"`
	Question    *string `json:"question,omitempty"`
	SelectedNum *int    `json:"selected_num,omitempty"`
	Total       *int    `json:"total,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
	Voted       *bool   `json:"voted,omitempty"`
}

// Posts defines model for Posts.
type Posts struct {
	Posts *[]Post `json:"posts,omitempty"`
}

// User defines model for User.
type User struct {
	HomeImage    *string `json:"homeImage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// Users defines model for Users.
type Users struct {
	Users *[]User `json:"users,omitempty"`
}

// PostAuthSignParams defines parameters for PostAuthSign.
type PostAuthSignParams struct {
	// IdToken 認証に利用するIDトークン
	IdToken string `json:"idToken"`
}

// PostV1PostsJSONBody defines parameters for PostV1Posts.
type PostV1PostsJSONBody struct {
	Options *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
	} `json:"options,omitempty"`
	Question *string `json:"question,omitempty"`
}

// GetV1PostsPrivateParams defines parameters for GetV1PostsPrivate.
type GetV1PostsPrivateParams struct {
	// Q 検索キーワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetV1PostsPublicParams defines parameters for GetV1PostsPublic.
type GetV1PostsPublicParams struct {
	// Q 検索ワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Pid 追加読み込みの基準
	Pid *string `form:"pid,omitempty" json:"pid,omitempty"`
}

// PostV1PostsPostIdPollsJSONBody defines parameters for PostV1PostsPostIdPolls.
type PostV1PostsPostIdPollsJSONBody struct {
	Option *struct {
		SelectNum *int `json:"select_num,omitempty"`
	} `json:"option,omitempty"`
}

// PatchV1UsersUserIdJSONBody defines parameters for PatchV1UsersUserId.
type PatchV1UsersUserIdJSONBody struct {
	Homeimage    *string `json:"homeimage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// PostV1PostsJSONRequestBody defines body for PostV1Posts for application/json ContentType.
type PostV1PostsJSONRequestBody PostV1PostsJSONBody

// PostV1PostsPostIdPollsJSONRequestBody defines body for PostV1PostsPostIdPolls for application/json ContentType.
type PostV1PostsPostIdPollsJSONRequestBody PostV1PostsPostIdPollsJSONBody

// PatchV1UsersUserIdJSONRequestBody defines body for PatchV1UsersUserId for application/json ContentType.
type PatchV1UsersUserIdJSONRequestBody PatchV1UsersUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/sign)
	PostAuthSign(w http.ResponseWriter, r *http.Request, params PostAuthSignParams)
	// Your GET endpoint
	// (GET /v1/frendships/{userId}/followers)
	GetV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /v1/frendships/{userId}/following)
	GetV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string)

	// (DELETE /v1/friendships/{userId})
	DeleteV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (POST /v1/friendships/{userId})
	PostV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /v1/friendships/{userId})
	PutV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)
	// 疎通確認でHealthCheck
	// (GET /v1/health)
	GetV1Health(w http.ResponseWriter, r *http.Request)

	// (POST /v1/posts)
	PostV1Posts(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /v1/posts/private)
	GetV1PostsPrivate(w http.ResponseWriter, r *http.Request, params GetV1PostsPrivateParams)
	// Your GET endpoint
	// (GET /v1/posts/public)
	GetV1PostsPublic(w http.ResponseWriter, r *http.Request, params GetV1PostsPublicParams)
	// Your GET endpoint
	// (GET /v1/posts/public/rank)
	GetV1PostsPublicRank(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /v1/posts/public/{post_id})
	GetV1PostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (DELETE /v1/posts/{post_id})
	DeleteV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /v1/posts/{post_id})
	GetV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (POST /v1/posts/{post_id}/polls)
	PostV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /v1/users)
	GetV1Users(w http.ResponseWriter, r *http.Request)

	// (POST /v1/users)
	PostV1Users(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/users/{user_id})
	DeleteV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /v1/users/{user_id})
	GetV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PATCH /v1/users/{user_id})
	PatchV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /v1/users/{user_id}/posted)
	GetV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string)

	// (GET /v1/users/{user_id}/settings)
	GetV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /v1/users/{user_id}/settings)
	PutV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /v1/users/{user_id}/voted)
	GetV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/sign)
func (_ Unimplemented) PostAuthSign(w http.ResponseWriter, r *http.Request, params PostAuthSignParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/frendships/{userId}/followers)
func (_ Unimplemented) GetV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/frendships/{userId}/following)
func (_ Unimplemented) GetV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/friendships/{userId})
func (_ Unimplemented) DeleteV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/friendships/{userId})
func (_ Unimplemented) PostV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v1/friendships/{userId})
func (_ Unimplemented) PutV1FriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 疎通確認でHealthCheck
// (GET /v1/health)
func (_ Unimplemented) GetV1Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/posts)
func (_ Unimplemented) PostV1Posts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/posts/private)
func (_ Unimplemented) GetV1PostsPrivate(w http.ResponseWriter, r *http.Request, params GetV1PostsPrivateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/posts/public)
func (_ Unimplemented) GetV1PostsPublic(w http.ResponseWriter, r *http.Request, params GetV1PostsPublicParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/posts/public/rank)
func (_ Unimplemented) GetV1PostsPublicRank(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/posts/public/{post_id})
func (_ Unimplemented) GetV1PostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/posts/{post_id})
func (_ Unimplemented) DeleteV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/posts/{post_id})
func (_ Unimplemented) GetV1PostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/posts/{post_id}/polls)
func (_ Unimplemented) PostV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/users)
func (_ Unimplemented) GetV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/users)
func (_ Unimplemented) PostV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/users/{user_id})
func (_ Unimplemented) DeleteV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/users/{user_id})
func (_ Unimplemented) GetV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /v1/users/{user_id})
func (_ Unimplemented) PatchV1UsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/users/{user_id}/posted)
func (_ Unimplemented) GetV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/users/{user_id}/settings)
func (_ Unimplemented) GetV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v1/users/{user_id}/settings)
func (_ Unimplemented) PutV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /v1/users/{user_id}/voted)
func (_ Unimplemented) GetV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthSign operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSign(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthSignParams

	headers := r.Header

	// ------------- Required header parameter "idToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("idToken")]; found {
		var IdToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "idToken", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "idToken", valueList[0], &IdToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "idToken", Err: err})
			return
		}

		params.IdToken = IdToken

	} else {
		err := fmt.Errorf("Header parameter idToken is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "idToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSign(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1FrendshipsUserIdFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetV1FrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1FrendshipsUserIdFollowers(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1FrendshipsUserIdFollowing operation middleware
func (siw *ServerInterfaceWrapper) GetV1FrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1FrendshipsUserIdFollowing(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PostV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutV1FriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PutV1FriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutV1FriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1Health operation middleware
func (siw *ServerInterfaceWrapper) GetV1Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Health(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Posts operation middleware
func (siw *ServerInterfaceWrapper) PostV1Posts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Posts(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1PostsPrivate operation middleware
func (siw *ServerInterfaceWrapper) GetV1PostsPrivate(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1PostsPrivateParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1PostsPrivate(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1PostsPublic operation middleware
func (siw *ServerInterfaceWrapper) GetV1PostsPublic(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1PostsPublicParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "pid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pid", r.URL.Query(), &params.Pid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1PostsPublic(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1PostsPublicRank operation middleware
func (siw *ServerInterfaceWrapper) GetV1PostsPublicRank(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1PostsPublicRank(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1PostsPublicPostId operation middleware
func (siw *ServerInterfaceWrapper) GetV1PostsPublicPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1PostsPublicPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1PostsPostId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1PostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1PostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1PostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetV1PostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1PostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1PostsPostIdPolls operation middleware
func (siw *ServerInterfaceWrapper) PostV1PostsPostIdPolls(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1PostsPostIdPolls(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1Users operation middleware
func (siw *ServerInterfaceWrapper) GetV1Users(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Users(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Users operation middleware
func (siw *ServerInterfaceWrapper) PostV1Users(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Users(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchV1UsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1UsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchV1UsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1UsersUserIdPosted operation middleware
func (siw *ServerInterfaceWrapper) GetV1UsersUserIdPosted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1UsersUserIdPosted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1UsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) GetV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1UsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutV1UsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) PutV1UsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutV1UsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1UsersUserIdVoted operation middleware
func (siw *ServerInterfaceWrapper) GetV1UsersUserIdVoted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1UsersUserIdVoted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign", wrapper.PostAuthSign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/frendships/{userId}/followers", wrapper.GetV1FrendshipsUserIdFollowers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/frendships/{userId}/following", wrapper.GetV1FrendshipsUserIdFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/friendships/{userId}", wrapper.DeleteV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/friendships/{userId}", wrapper.PostV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/friendships/{userId}", wrapper.PutV1FriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetV1Health)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/posts", wrapper.PostV1Posts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/private", wrapper.GetV1PostsPrivate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/public", wrapper.GetV1PostsPublic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/public/rank", wrapper.GetV1PostsPublicRank)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/public/{post_id}", wrapper.GetV1PostsPublicPostId)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/posts/{post_id}", wrapper.DeleteV1PostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/{post_id}", wrapper.GetV1PostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/posts/{post_id}/polls", wrapper.PostV1PostsPostIdPolls)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users", wrapper.GetV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/users", wrapper.PostV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/users/{user_id}", wrapper.DeleteV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/{user_id}", wrapper.GetV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/users/{user_id}", wrapper.PatchV1UsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/{user_id}/posted", wrapper.GetV1UsersUserIdPosted)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/{user_id}/settings", wrapper.GetV1UsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/users/{user_id}/settings", wrapper.PutV1UsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/{user_id}/voted", wrapper.GetV1UsersUserIdVoted)
	})

	return r
}
