// Package oas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oas

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthSignResponse defines model for AuthSignResponse.
type AuthSignResponse struct {
	// Registered ユーザー作成済みかどうか
	Registered bool            `json:"registered"`
	User       *AuthSignedUser `json:"user,omitempty"`
}

// AuthSignedUser defines model for AuthSignedUser.
type AuthSignedUser struct {
	// Id ユーザーUUID
	Id openapi_types.UUID `json:"id"`

	// Name 表示名
	Name string `json:"name"`

	// ThumbnailUrl サムネイル画像URL
	ThumbnailUrl string `json:"thumbnail_url"`

	// UniqueId ユーザーが設定する任意ID
	UniqueId string `json:"unique_id"`
}

// Post defines model for Post.
type Post struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Iconimage *string `json:"iconimage,omitempty"`
	Options   *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
		Votes     *int    `json:"votes,omitempty"`
	} `json:"options,omitempty"`
	PostId      *string `json:"post_id,omitempty"`
	Question    *string `json:"question,omitempty"`
	SelectedNum *int    `json:"selected_num,omitempty"`
	Total       *int    `json:"total,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
	Voted       *bool   `json:"voted,omitempty"`
}

// Posts defines model for Posts.
type Posts struct {
	Posts *[]Post `json:"posts,omitempty"`
}

// User defines model for User.
type User struct {
	HomeImage    *string `json:"homeImage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// Users defines model for Users.
type Users struct {
	Users *[]User `json:"users,omitempty"`
}

// PostAuthSignParams defines parameters for PostAuthSign.
type PostAuthSignParams struct {
	// IdToken 認証に利用するIDトークン
	IdToken string `json:"idToken"`
}

// PostPostsJSONBody defines parameters for PostPosts.
type PostPostsJSONBody struct {
	Options *[]struct {
		Answer    *string `json:"answer,omitempty"`
		SelectNum *int    `json:"select_num,omitempty"`
	} `json:"options,omitempty"`
	Question *string `json:"question,omitempty"`
}

// GetPostsPrivateParams defines parameters for GetPostsPrivate.
type GetPostsPrivateParams struct {
	// Q 検索キーワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetPostsPublicParams defines parameters for GetPostsPublic.
type GetPostsPublicParams struct {
	// Q 検索ワード
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Pid 追加読み込みの基準
	Pid *string `form:"pid,omitempty" json:"pid,omitempty"`
}

// PostPostsPostIdPollsJSONBody defines parameters for PostPostsPostIdPolls.
type PostPostsPostIdPollsJSONBody struct {
	Option *struct {
		SelectNum *int `json:"select_num,omitempty"`
	} `json:"option,omitempty"`
}

// PatchUsersUserIdJSONBody defines parameters for PatchUsersUserId.
type PatchUsersUserIdJSONBody struct {
	Homeimage    *string `json:"homeimage,omitempty"`
	Iconimage    *string `json:"iconimage,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Name         *string `json:"name,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody PostPostsJSONBody

// PostPostsPostIdPollsJSONRequestBody defines body for PostPostsPostIdPolls for application/json ContentType.
type PostPostsPostIdPollsJSONRequestBody PostPostsPostIdPollsJSONBody

// PatchUsersUserIdJSONRequestBody defines body for PatchUsersUserId for application/json ContentType.
type PatchUsersUserIdJSONRequestBody PatchUsersUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/sign)
	PostAuthSign(w http.ResponseWriter, r *http.Request, params PostAuthSignParams)
	// Your GET endpoint
	// (GET /frendships/{userId}/followers)
	GetFrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /frendships/{userId}/following)
	GetFrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string)

	// (DELETE /friendships/{userId})
	DeleteFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (POST /friendships/{userId})
	PostFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /friendships/{userId})
	PutFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (POST /posts)
	PostPosts(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /posts/private)
	GetPostsPrivate(w http.ResponseWriter, r *http.Request, params GetPostsPrivateParams)
	// Your GET endpoint
	// (GET /posts/public)
	GetPostsPublic(w http.ResponseWriter, r *http.Request, params GetPostsPublicParams)
	// Your GET endpoint
	// (GET /posts/public/rank)
	GetPostsPublicRank(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /posts/public/{post_id})
	GetPostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (DELETE /posts/{post_id})
	DeletePostsPostId(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /posts/{post_id})
	GetPostsPostId(w http.ResponseWriter, r *http.Request, postId string)

	// (POST /posts/{post_id}/polls)
	PostPostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string)
	// Your GET endpoint
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request)

	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request)

	// (DELETE /users/{user_id})
	DeleteUsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /users/{user_id})
	GetUsersUserId(w http.ResponseWriter, r *http.Request, userId string)

	// (PATCH /users/{user_id})
	PatchUsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /users/{user_id}/posted)
	GetUsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string)

	// (GET /users/{user_id}/settings)
	GetUsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)

	// (PUT /users/{user_id}/settings)
	PutUsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string)
	// Your GET endpoint
	// (GET /users/{user_id}/voted)
	GetUsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/sign)
func (_ Unimplemented) PostAuthSign(w http.ResponseWriter, r *http.Request, params PostAuthSignParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /frendships/{userId}/followers)
func (_ Unimplemented) GetFrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /frendships/{userId}/following)
func (_ Unimplemented) GetFrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /friendships/{userId})
func (_ Unimplemented) DeleteFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /friendships/{userId})
func (_ Unimplemented) PostFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /friendships/{userId})
func (_ Unimplemented) PutFriendshipsUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /posts)
func (_ Unimplemented) PostPosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /posts/private)
func (_ Unimplemented) GetPostsPrivate(w http.ResponseWriter, r *http.Request, params GetPostsPrivateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /posts/public)
func (_ Unimplemented) GetPostsPublic(w http.ResponseWriter, r *http.Request, params GetPostsPublicParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /posts/public/rank)
func (_ Unimplemented) GetPostsPublicRank(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /posts/public/{post_id})
func (_ Unimplemented) GetPostsPublicPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /posts/{post_id})
func (_ Unimplemented) DeletePostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /posts/{post_id})
func (_ Unimplemented) GetPostsPostId(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /posts/{post_id}/polls)
func (_ Unimplemented) PostPostsPostIdPolls(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /users/{user_id})
func (_ Unimplemented) DeleteUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /users/{user_id})
func (_ Unimplemented) GetUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /users/{user_id})
func (_ Unimplemented) PatchUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /users/{user_id}/posted)
func (_ Unimplemented) GetUsersUserIdPosted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users/{user_id}/settings)
func (_ Unimplemented) GetUsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /users/{user_id}/settings)
func (_ Unimplemented) PutUsersUserIdSettings(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Your GET endpoint
// (GET /users/{user_id}/voted)
func (_ Unimplemented) GetUsersUserIdVoted(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthSign operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSign(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthSignParams

	headers := r.Header

	// ------------- Required header parameter "idToken" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("idToken")]; found {
		var IdToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "idToken", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "idToken", valueList[0], &IdToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "idToken", Err: err})
			return
		}

		params.IdToken = IdToken

	} else {
		err := fmt.Errorf("Header parameter idToken is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "idToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSign(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFrendshipsUserIdFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetFrendshipsUserIdFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFrendshipsUserIdFollowers(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFrendshipsUserIdFollowing operation middleware
func (siw *ServerInterfaceWrapper) GetFrendshipsUserIdFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFrendshipsUserIdFollowing(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteFriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PostFriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFriendshipsUserId operation middleware
func (siw *ServerInterfaceWrapper) PutFriendshipsUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFriendshipsUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPosts(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostsPrivate operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPrivate(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsPrivateParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPrivate(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostsPublic operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublic(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsPublicParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "pid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pid", r.URL.Query(), &params.Pid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPublic(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostsPublicRank operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublicRank(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPublicRank(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostsPublicPostId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublicPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPublicPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePostsPostId operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPostId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostsPostId(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPostsPostIdPolls operation middleware
func (siw *ServerInterfaceWrapper) PostPostsPostIdPolls(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPostsPostIdPolls(w, r, postId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUsersUserId(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersUserIdPosted operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdPosted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserIdPosted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// PutUsersUserIdSettings operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserIdSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUsersUserIdSettings(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersUserIdVoted operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdVoted(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserIdVoted(w, r, userId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign", wrapper.PostAuthSign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/frendships/{userId}/followers", wrapper.GetFrendshipsUserIdFollowers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/frendships/{userId}/following", wrapper.GetFrendshipsUserIdFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/friendships/{userId}", wrapper.DeleteFriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/friendships/{userId}", wrapper.PostFriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/friendships/{userId}", wrapper.PutFriendshipsUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/posts", wrapper.PostPosts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/private", wrapper.GetPostsPrivate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/public", wrapper.GetPostsPublic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/public/rank", wrapper.GetPostsPublicRank)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/public/{post_id}", wrapper.GetPostsPublicPostId)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/posts/{post_id}", wrapper.DeletePostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/{post_id}", wrapper.GetPostsPostId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/posts/{post_id}/polls", wrapper.PostPostsPostIdPolls)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{user_id}", wrapper.DeleteUsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}", wrapper.GetUsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{user_id}", wrapper.PatchUsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/posted", wrapper.GetUsersUserIdPosted)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/settings", wrapper.GetUsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{user_id}/settings", wrapper.PutUsersUserIdSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/voted", wrapper.GetUsersUserIdVoted)
	})

	return r
}
