version: "2"
sql:
  - engine: "mysql"
    queries: "./sql/"
    schema: "../migration/schema/"
    gen:
      go:
        package: "sqlcgenerate"
        out: "./sqlcgenerate/"
        emit_json_tags: true
        json_tags_case_style: "camel"
